# Generated by Django 5.1.2 on 2025-10-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('HA', 'Happy'), ('EX', 'Excited'), ('CA', 'Calm'), ('GR', 'Grateful'), ('HOL', 'Hopeful'), ('SA', 'Sad'), ('AN', 'Angry'), ('ANX', 'Anxious'), ('BO', 'Bored'), ('LO', 'Lonely'), ('NI', 'Indifferent'), ('PE', 'Pensive'), ('NO', 'Nostalgic'), ('BI', 'Bittersweet'), ('AM', 'Ambivalent'), ('RO', 'Romantic'), ('PL', 'Playful'), ('ME', 'Melancholic'), ('MO', 'Motivated'), ('FR', 'Frustrated'), ('TI', 'Tiring'), ('EN', 'Energetic'), ('SP', 'Spiritual'), ('EXH', 'Exhilarated'), ('HOS', 'Hopeless'), ('FA', 'Faithful'), ('AW', 'Awkward'), ('CO', 'Confident'), ('SU', 'Surprised'), ('DI', 'Disappointed'), ('FO', 'Forgiving')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='TrackPlayed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('audio_url', models.URLField()),
                ('duration', models.FloatField()),
                ('played_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
