# Generated by Django 5.1.2 on 2025-12-06 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('type', models.CharField(choices=[('HA', 'Happy'), ('EX', 'Excited'), ('CA', 'Calm'), ('GR', 'Grateful'), ('HOL', 'Hopeful'), ('SA', 'Sad'), ('AN', 'Angry'), ('ANX', 'Anxious'), ('BO', 'Bored'), ('LO', 'Lonely'), ('NI', 'Indifferent'), ('PE', 'Pensive'), ('NO', 'Nostalgic'), ('BI', 'Bittersweet'), ('AM', 'Ambivalent'), ('RO', 'Romantic'), ('PL', 'Playful'), ('ME', 'Melancholic'), ('MO', 'Motivated'), ('FR', 'Frustrated'), ('TI', 'Tiring'), ('EN', 'Energetic'), ('SP', 'Spiritual'), ('EXH', 'Exhilarated'), ('HOS', 'Hopeless'), ('FA', 'Faithful'), ('AW', 'Awkward'), ('CO', 'Confident'), ('SU', 'Surprised'), ('DI', 'Disappointed'), ('FO', 'Forgiving')], db_index=True, max_length=3)),
                ('upload_date', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookMarkedSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(db_index=True, max_length=255)),
                ('track_name', models.CharField(blank=True, max_length=255, null=True)),
                ('artist_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('image_url', models.URLField()),
                ('audio_url', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrackPlayed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(db_index=True, max_length=255)),
                ('track_name', models.CharField(blank=True, max_length=255, null=True)),
                ('artist_name', models.CharField(blank=True, max_length=255, null=True)),
                ('album_name', models.CharField(blank=True, max_length=255, null=True)),
                ('releasedate', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('played_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('image_url', models.URLField()),
                ('audio_url', models.URLField()),
                ('duration', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMoodSwing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(db_index=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBookmarkedSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmarked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mood.bookmarkedsong')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'song')},
            },
        ),
    ]
