# Generated by Django 5.1.2 on 2025-10-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookMarkedSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('image_url', models.URLField()),
                ('audio_url', models.URLField()),
                ('duration', models.FloatField()),
                ('played_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='moods',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='moods',
            name='type',
            field=models.CharField(choices=[('HA', 'Happy'), ('EX', 'Excited'), ('CA', 'Calm'), ('GR', 'Grateful'), ('HOL', 'Hopeful'), ('SA', 'Sad'), ('AN', 'Angry'), ('ANX', 'Anxious'), ('BO', 'Bored'), ('LO', 'Lonely'), ('NI', 'Indifferent'), ('PE', 'Pensive'), ('NO', 'Nostalgic'), ('BI', 'Bittersweet'), ('AM', 'Ambivalent'), ('RO', 'Romantic'), ('PL', 'Playful'), ('ME', 'Melancholic'), ('MO', 'Motivated'), ('FR', 'Frustrated'), ('TI', 'Tiring'), ('EN', 'Energetic'), ('SP', 'Spiritual'), ('EXH', 'Exhilarated'), ('HOS', 'Hopeless'), ('FA', 'Faithful'), ('AW', 'Awkward'), ('CO', 'Confident'), ('SU', 'Surprised'), ('DI', 'Disappointed'), ('FO', 'Forgiving')], db_index=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='moods',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='trackplayed',
            name='played_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='trackplayed',
            name='track_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
