# Generated by Django 5.1.2 on 2025-12-12 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0003_remove_customuser_bookmarked_songs'),
        ('mood', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBookmarkedSong',
        ),
    ]
