# Generated by Django 5.1.2 on 2025-09-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moods',
            name='type',
            field=models.CharField(choices=[('HA', 'Happy'), ('EX', 'Excited'), ('CA', 'Calm'), ('GR', 'Grateful'), ('HOL', 'Hopeful'), ('SA', 'Sad'), ('AN', 'Angry'), ('ANX', 'Anxious'), ('BO', 'Bored'), ('LO', 'Lonely'), ('NI', 'Indifferent'), ('PE', 'Pensive'), ('NO', 'Nostalgic'), ('BI', 'Bittersweet'), ('AM', 'Ambivalent'), ('RO', 'Romantic'), ('PL', 'Playful'), ('ME', 'Melancholic'), ('MO', 'Motivated'), ('FR', 'Frustrated'), ('TI', 'Tiring'), ('EN', 'Energetic'), ('SP', 'Spiritual'), ('EXH', 'Exhilarated'), ('HOS', 'Hopeless'), ('FA', 'Faithful'), ('AW', 'Awkward'), ('CO', 'Confident'), ('SU', 'Surprised'), ('DI', 'Disappointed'), ('FO', 'Forgiving')], max_length=3),
        ),
        migrations.AlterField(
            model_name='moods',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
