# Generated by Django 5.1.2 on 2025-10-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0002_alter_moods_type_alter_moods_upload_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackPlayed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('audio_url', models.URLField()),
                ('duration', models.FloatField()),
                ('played_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
