# Generated by Django 5.1.2 on 2025-10-07 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
