# Generated by Django 5.1.2 on 2025-10-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0001_initial'),
        ('mood', '0003_userbookmarkedsong'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bookmarked_songs',
            field=models.ManyToManyField(through='mood.UserBookmarkedSong', to='mood.bookmarkedsong'),
        ),
    ]
