# Generated by Django 5.1.2 on 2025-12-12 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bookmarked_songs',
        ),
    ]
